github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # configure whether Gitpod registers itself as a status check to pull requests
    addCheck: false

tasks:
  - name: download pcap
    init: python3 scripts/get_pcap.py
  
  - name: download docker images
    init: docker-compose pull 

  - name: start services
    command: docker-compose up -d

ports:

  # Confluent Control Center
  - port: 9021
    onOpen: open-browser
    visibility: public

  # Kibana UI
  - port: 5601
    onOpen: open-browser
    visibility: public

  # Confluent Sigma UI
  - port: 8080
    onOpen: open-browser
    visibility: public

  # zookeeper
  - port: 2181
    onOpen: ignore
    
  # Confluent Server (broker)
  - port: 9092
    onOpen: ignore
    
  # Confluent Server (REST)
  - port: 8090
    onOpen: ignore
    
  # Schema Registry
  - port: 8081
    onOpen: ignore

  # Confluent REST Proxy
  - port: 8082
    onOpen: ignore
    
  # Kafka Connect
  - port: 8083
    onOpen: ignore
    
  # ksqlDB
  - port: 8088
    onOpen: ignore
  
  # Splunk Event Generator
  - port: 9500
    onOpen: ignore

  # ignore a bunch of ports
  - port: 3333
    onOpen: ignore

  - port: 6379
    onOpen: ignore

  - port: 9000-10000
    onOpen: ignore